keys:
  # Laptop age key
  - &laptop age1dyegtj68gpyhwvus4wlt8azyas2sslwwt8fwyqwz3vu2jffl8chsk2afne
  # Server age key  
  - &server age14rghg6wtzujzmhd0hxhf8rp3vkj8d7uu6f3ppm2grcj5c0gfn4wqz3l0zh

creation_rules:
  # Database secrets (server only)
  - path_regex: secrets/database\.yaml$
    key_groups:
      - age:
          - *server
  
  # Surveillance secrets (server only)
  - path_regex: secrets/surveillance\.yaml$
    key_groups:
      - age:
          - *server
  
  # Admin secrets (both laptop and server)
  - path_regex: secrets/admin\.yaml$
    key_groups:
      - age:
          - *laptop
          - *server
  
  # User secrets (both laptop and server)
  - path_regex: secrets/users\.yaml$
    key_groups:
      - age:
          - *laptop
          - *server

  # Default rule for any other secrets
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *laptop
          - *server