#ENC[AES256_GCM,data:6+MwpYVZHISgq1AQ5VO46OCmsglwsuiUFlUGIgP42o3mHABES4tWgO+kWg==,iv:T9eY7dnbcrbq+/9UnFhAiG9r4Vo1ecCdfjlPE3GP43A=,tag:umfrKES+dhxQF486Hu4dFQ==,type:comment]
postgres:
    #ENC[AES256_GCM,data:4H9yvgAZjMxOKAlqF1GJMsPfX4jlp9FFmTP/c9a7DVB+VzcotXNgnFmqcmX1/mp+Hrwz5e+yrNgWKjLU2Q==,iv:8+Ps1iyqnhKdUw0LQSmIyMd4ao7U3EH5R93miv/3YcU=,tag:3SFXAP74Ce5bjjn+n9JI5A==,type:comment]
    password: ENC[AES256_GCM,data:Np2G59OO49wg5oeycMJf4JZh9Ob53ckVTQ==,iv:fhsHz1Kk+Rf3U4C8MgjddpIJ+2YXoqS/LhFSoc/U0AM=,tag:3/ND12jMJDP3xFPIa7++iA==,type:str]
    user: ENC[AES256_GCM,data:MTtpoqlssgw86aVgkQ==,iv:5oKleTIDQJoozLChNfTBw5EcxBWp03NNpLSq/YQ26so=,tag:sdInFUjBifZ+1K9dO/2HUg==,type:str]
    database: ENC[AES256_GCM,data:r6tSz0xTf9QKx6N6dWdrAc44,iv:kq3InNI6+b/zhNsNKkRByOD15SPdFgSILnpEAwJtuK0=,tag:/PYbYA2Rn3wBYLhkmX1eGg==,type:str]
    host: ENC[AES256_GCM,data:Pka3lhqm/AnY,iv:A5wwgGjvaL5EOiCse65gasaxE3zJ5rk2QGNP1piiXDY=,tag:4pEmX9IxbZSvVGwlGAKdgg==,type:str]
    port: ENC[AES256_GCM,data:OKlSQg==,iv:bdY/cuMjco009pl6q3aza1LG0etJcnnKa+8Qnhr+Ig4=,tag:HuRlNsPw6LBWE7dnEvX6pg==,type:int]
#ENC[AES256_GCM,data:LxQWu8BPgRCBJlLDZPc4oSrMYEfuDlFVPFdOi1xzsMN5Knk=,iv:Gws7w6DKIYuBvp8W75HV9xO0k7bkylSRsu4CjavXWDY=,tag:J570wQbYq6bs/fbZAQekVA==,type:comment]
connection_string: ENC[AES256_GCM,data:q1UjiDWEe/XmtVIcZqHGsuwyv2va6EOWyNJPvDgkcrIv7oyo5ycRzUtne33BYiTbpnGLwMVGjIyb3MrzCywpykkcpnoSVe4meOVq20KrpajE82q6okI=,iv:QsYkhw6a/K0WLAGrcBAoqUL+rGe+OuKiRdRVIW22c18=,tag:RAB+LAjIN4vSmk0o1C3edg==,type:str]
#ENC[AES256_GCM,data:yhxye3kD7s32Fr1k1OR3pzFN5ixmdx+YvIfrDUHI,iv:7Hu8s/OAEhcnHiWwXte3j4ZGf2AeBfZEqOxgSHIL208=,tag:Iuut3kyZNFB8Xi8vU1f+RQ==,type:comment]
redis:
    #ENC[AES256_GCM,data:H8UtnZpxMbGNgoqyhWA/OUrjYELL7jsYd4GDD78kKjx5iGcCTVvUBfhnXZzMsUoMiZisT7vB0ZIFb2YPcg==,iv:063DX7uuIkFdyHBJSpIF8MKGNCkmyUKlDhji3rxBUqs=,tag:1jUYl4i2KG4RGwfugO+XOw==,type:comment]
    password: ""
    host: ENC[AES256_GCM,data:NUEB9Yhue2ci,iv:i5uVy7J1K0KVtionuZU9bi//7QEh9H2ywPbHN1XuyCM=,tag:yZSLe7BddvdUfpM2bDVrXw==,type:str]
    port: ENC[AES256_GCM,data:/lqBVw==,iv:KTf6hMPzWdZb7ldABhodsO24KLBO/rKlmYNALgy/hps=,tag:axy2aqzCMrtJ+o3y/FxfNw==,type:int]
sops:
    age:
        - recipient: age14rghg6wtzujzmhd0hxhf8rp3vkj8d7uu6f3ppm2grcj5c0gfn4wqz3l0zh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVjdpTVlPaEh5UmszS1ln
            SksrL0NCNVBuWEk0VTNCdzJ1ZG9JdG1OTmpjCm1YZWNQellyZUJWNzlTelJjNTZp
            NlJHYlY3QVZmZXh1dXJHTldYMDRWSWsKLS0tIE9XSDR1N0V6NUIvSDExNGJ0OGJv
            TWpJYjlXSWczeG8rSG01N3ZNd21uTmMK+ylkLc8I+4nqUlS8Wux98y8RfEkNTh6+
            mfb1S9h5TcxQNpckD8HHm/seyoo5u/bfcslAwEnUaxHRD5p+8nwYUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-29T06:42:01Z"
    mac: ENC[AES256_GCM,data:HRtyLOIrGHlQW91+FCExYeIG+XEUmQjpLho8sWbONANL4jbJ6rs+VE0ey5Y96uMycpZmbRHzD58LmxhTPzgk9fW7T/sZcNrnF4xQrC+rz239JrQHAUq9aVXLGgFTbrR3K+bvjxxB4vs/1G79Cv+e0IEDWr7EvPYnjJztYZ6C8oc=,iv:7H0B+hrqtau/ZLQcTZspJrByJ4iblEuX1eHm7JE3t1M=,tag:aN3Sd+LiW7eKdEXQ9edlyg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
